import type {
  CommandCenterControlResponse,
  CommandCenterDemandResponse,
} from './command-center';

export const COMMAND_CENTER_CONTROL_CLUSTERS: CommandCenterControlResponse['clusters'] =
  [
    {
      id: 'core-ops',
      label: 'Core Ops',
      engines: [
        {
          id: 'doc-specialist',
          name: 'Doc Specialist',
          task: 'drift-repair',
          model: 'Service-native',
          tier: 'service-native',
          allowedSkills: ['knowledge-pack', 'telemetry'],
          networkMode: 'service-native',
          timeoutLabel: 'Continuous',
          approvalClass: 'service-native',
        },
        {
          id: 'integration-agent',
          name: 'Integration Agent',
          task: 'integration-workflow',
          model: 'claude-3-5-sonnet',
          tier: 'balanced',
          allowedSkills: ['documentParser', 'normalizer'],
          networkMode: 'local',
          timeoutLabel: '600s',
          approvalClass: 'bounded',
        },
        {
          id: 'system-monitor-agent',
          name: 'System Monitor Agent',
          task: 'system-monitor',
          model: 'gpt-4o-mini',
          tier: 'cheap',
          allowedSkills: ['documentParser'],
          networkMode: 'local',
          timeoutLabel: '30s',
          approvalClass: 'bounded',
        },
        {
          id: 'build-refactor-agent',
          name: 'Build Refactor Agent',
          task: 'build-refactor',
          model: 'claude-3-5-sonnet',
          tier: 'balanced',
          allowedSkills: ['workspacePatch', 'testRunner'],
          networkMode: 'local',
          timeoutLabel: '300s',
          approvalClass: 'approval-gated',
        },
      ],
    },
    {
      id: 'trust-boundaries',
      label: 'Trust Boundaries',
      engines: [
        {
          id: 'security-agent',
          name: 'Security Audit Agent',
          task: 'security-audit',
          model: 'claude-3-5-sonnet',
          tier: 'balanced',
          allowedSkills: ['documentParser', 'normalizer'],
          networkMode: 'local',
          timeoutLabel: '600s',
          approvalClass: 'bounded',
        },
        {
          id: 'qa-verification-agent',
          name: 'QA Verification Agent',
          task: 'qa-verification',
          model: 'claude-3-5-sonnet',
          tier: 'balanced',
          allowedSkills: ['testRunner'],
          networkMode: 'local',
          timeoutLabel: '300s',
          approvalClass: 'bounded',
        },
        {
          id: 'skill-audit-agent',
          name: 'Skill Audit Agent',
          task: 'skill-audit',
          model: 'claude-3-5-sonnet',
          tier: 'balanced',
          allowedSkills: ['testRunner', 'documentParser'],
          networkMode: 'local',
          timeoutLabel: '300s',
          approvalClass: 'bounded',
        },
      ],
    },
    {
      id: 'knowledge-content',
      label: 'Knowledge + Content',
      engines: [
        {
          id: 'data-extraction-agent',
          name: 'Data Extraction Agent',
          task: 'data-extraction',
          model: 'gpt-4o-mini',
          tier: 'cheap',
          allowedSkills: ['documentParser', 'normalizer'],
          networkMode: 'local',
          timeoutLabel: '90s',
          approvalClass: 'bounded',
        },
        {
          id: 'normalization-agent',
          name: 'Normalization Agent',
          task: 'normalize-data',
          model: 'gpt-4o-mini',
          tier: 'cheap',
          allowedSkills: ['normalizer', 'documentParser'],
          networkMode: 'local',
          timeoutLabel: '120s',
          approvalClass: 'bounded',
        },
        {
          id: 'summarization-agent',
          name: 'Summarization Agent',
          task: 'summarize-content',
          model: 'gpt-4o-mini',
          tier: 'cheap',
          allowedSkills: ['documentParser', 'normalizer'],
          networkMode: 'local',
          timeoutLabel: '60s',
          approvalClass: 'bounded',
        },
        {
          id: 'content-agent',
          name: 'Content Agent',
          task: 'content-generate',
          model: 'gpt-4o-mini',
          tier: 'cheap',
          allowedSkills: ['documentParser'],
          networkMode: 'local',
          timeoutLabel: '180s',
          approvalClass: 'bounded',
        },
      ],
    },
    {
      id: 'community-market',
      label: 'Community + Market',
      engines: [
        {
          id: 'reddit-helper',
          name: 'Reddit Helper',
          task: 'reddit-response',
          model: 'Service-native',
          tier: 'service-native',
          allowedSkills: ['draft-log', 'devvit-queue', 'telemetry'],
          networkMode: 'service-native',
          timeoutLabel: 'Continuous',
          approvalClass: 'service-native',
        },
        {
          id: 'market-research-agent',
          name: 'Market Research Agent',
          task: 'market-research',
          model: 'gpt-4o-mini',
          tier: 'cheap',
          allowedSkills: ['sourceFetch'],
          networkMode: 'allowlisted',
          timeoutLabel: '120s',
          approvalClass: 'bounded',
        },
      ],
    },
  ];

export const COMMAND_CENTER_DEMAND_SEGMENTS: Array<
  Omit<CommandCenterDemandResponse['segments'][number], 'liveSignalCount' | 'state'>
> = [
  {
    id: 'cash-velocity',
    label: 'Cash Velocity',
    clusterLabels: ['payments and backend', 'preview vs production', 'core instability'],
    staticWeight: 5,
  },
  {
    id: 'security-exposure',
    label: 'Security Exposure',
    clusterLabels: ['security exposure', 'zero trust', 'segmentation'],
    staticWeight: 5,
  },
  {
    id: 'skills-supply-chain',
    label: 'Skills Supply Chain',
    clusterLabels: ['skills supply chain', 'prompt injection', 'extension trust'],
    staticWeight: 4,
  },
  {
    id: 'autonomy-collapse',
    label: 'Autonomy Collapse',
    clusterLabels: ['approval loops', 'execution stalls', 'non-execution'],
    staticWeight: 4,
  },
  {
    id: 'hardening-runtime',
    label: 'Hardening + Runtime',
    clusterLabels: ['docker vs vm', 'least privilege', 'tool calling'],
    staticWeight: 4,
  },
  {
    id: 'debug-blindness',
    label: 'Debug Blindness',
    clusterLabels: ['no logs', 'no stack trace', 'wrong explanation'],
    staticWeight: 3,
  },
  {
    id: 'data-shape-drift',
    label: 'Data Shape Drift',
    clusterLabels: ['normalization', 'schema mapping', 'dedupe'],
    staticWeight: 3,
  },
];
